### ISSUE TITLE
Some of the links are dead

### ISSUE THREAD

**Issue by onurcanbektas** [desireevl/awesome-quantum-computing#26]
Some of links of the books are dead, can you just give the references of those books ?

**Comment by nicklambourne** [comment]
The only book link that is dead is _Quantum Computation and Quantum Information - Michael Nielsen and Isaac Chuang, 2nd ed., 2010, Cambridge University Press_.

**Comment by onurcanbektas** [comment]
> The only book link that is dead is _Quantum Computation and Quantum Information - Michael Nielsen and Isaac Chuang, 2nd ed., 2010, Cambridge University Press_. Would have saved some time if you had included that info in your issue.

Well, you are right. My assumption was that there were other links that are dead; apparently, that assumption was wrong. Thanks for pointing out.

**Comment by desireevl** [comment]
Hi thanks for pointing this out, I have gone through all the resources and updated the dead links!

**Comment by onurcanbektas** [comment]
Thanks a lot @desireevl .

**Comment by sreevadlamani** [comment]
Hi @desireevl , this link is the quantum computer programming course from the Stanford university and I think would be a great addition to these excellent resources. https://cs269q.stanford.edu/syllabus.html?fbclid=IwAR09_JNstMi4WVU4oMHDpWR6xWaSISlrYPjWTUTnhcRdEQhzpoOTRgQN8LI 
Check it out!

**Comment by desireevl** [comment]
@sreevadlamani thanks, just added it! For future reference you are welcome to create a PR with your suggestions.
