### ISSUE TITLE
Quantum Computing Report needs to be added to the Blogs

### ISSUE THREAD

**Issue by dougfinke1** [desireevl/awesome-quantum-computing#53]
The Quantum Computing Report needs to be added to the list of Blogs.  The web site is at https://quantumcomputingreport.com.

Thank-you.

**Comment by desireevl** [comment]
Hi thanks for suggesting this. I am unsure if this would be a good resource to add as it seems to be running on a paid membership model - not FOSS

**Comment by dougfinke1** [comment]
Hi Desiree,

Thank you for looking at this.  First, I should point out that large portions of the Quantum Computing Report are free.  We do have some premium sections that contain some proprietary data bases, but a large many readers can view the website and find great value without paying anything.  Second, I should note that have a FOSS resources is not listed as a pre-requisite for being listed.  And third, there are already a great many of items listed that require a payment to use.  For example, the Amazon Braket service is requires payment to use, most, if not all of the books need to be purchased, and even some of the courses like Brilliant.org will require a payment if someone wants to go through the course.

So I think it is not fair or consistent to exclude the Quantum Computing Report which has many portions of the site that is completely free when you have all these other things listed that are not FOSS.

I request you reconsider.


Thanks,

Doug Finke
Managing Editor
Quantum Computing Report
Where Qubits Entangle with Commerce
Email: dfinke@quantumcomputingreport.com<mailto:dfinke@quantumcomputingreport.com>
Web: https://quantumcomputingreport.com<https://urldefense.proofpoint.com/v2/url?u=https-3A__nam01.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Fcontactmonkey.com-252Fapi-252Fv1-252Ftracker-253Fcm-5Fsession-253D56e0180e-2D485d-2D415c-2D9e5e-2D51c778324e05-2526cm-5Ftype-253Dlink-2526cm-5Flink-253D243d49b2-2D140c-2D417e-2D8d22-2D6ff88e6fd99b-2526cm-5Fdestination-253Dhttps-253A-252F-252Fquantumcomputingreport.com-26data-3D02-257C01-257C-257Ca0d4ae142d8745dfb88108d57e22e26e-257C84df9e7fe9f640afb435aaaaaaaaaaaa-257C1-257C0-257C636553610643412903-26sdata-3DBF3OT8kBg-252BGz-252FZXZYOU-252BpN9KYV0bf8J2AxsAfra59bA-253D-26reserved-3D0&d=DwMFaQ&c=Ftw_YSVcGmqQBvrGwAZugGylNRkk-uER0-5bY94tjsc&r=mQ6E5w6ZyAQSFAxjF9AqZZFThuhUh5gY5hF1TnSO954&m=eUIarWab_4-kxc-mtN9cmcqZrZabuaVGuOwmMCPxtfU&s=LOBfUO-A1IZh5UGj0gAni6xCzqvsjfGVWfhH6Q36lPA&e=>

**Comment by desireevl** [comment]
Sorry about that, my last comment got cut off. I was going to say as some parts are not FOSS I can't see all the content that is available and won't be able to make an accurate description of what is offered. Please feel free to make a pull request with a description of what the site offers and I can merge that to the list.
